    name: Deploy to AWS Elastic Beanstalk
    on:
      push:
        branches:
          - main
    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20.12.2'
    
          - name: Install pnpm
            run: npm install -g pnpm
    
          - name: Install dependencies
            run: pnpm install
    
          - name: Build application
            run: pnpm build
    
          - name: Deploy to AWS Elastic Beanstalk
            uses: aws-actions/aws-elastic-beanstalk-deploy-action@v2
            with:
              aws-region: ${{ secrets.AWS_REGION }}
              application-name: your-application-name
              environment-name: your-environment-name
              deployment-package: ./
              version-label: ${{ github.sha }}
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}